apiVersion: v1
kind: Service
metadata:
  name: fast-api-service    # Do not change this name
spec:

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-backend
spec:
  selector:
    
  template:
    metadata:
      
    spec:
